# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('type', models.IntegerField(choices=[('密码找回', 0), ('转账', 1), ('登录验证', 2)], default=0, verbose_name='类型')),
                ('is_valid', models.BooleanField(default=1, verbose_name='是否有效')),
                ('active_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='有效期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
