# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time', '-id', 'title']},
        ),
    ]
